spring:
  profiles:
    active: dev

server:
  port: 80

auth-server:
  service:
    name: ${SERVICE_NAME}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3309/hyuuny?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password1!
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000

jwt:
  token:
    secret: ${JASYPT_PASSWORD}
    duration:
      access-token: 36000000
      refresh-token: 3600000000